blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/microsoft/Documentarian/discussions/new?category=q-a
    about: >-
      If you have a question about a module, the docs, or this project, ask it here.
  - name: Suggest a new feature or change to an existing one
    url: https://github.com/microsoft/Documentarian/discussions/new?category=code-proposals
    about: >-
      If you have an idea for a feature or change in code functionality, suggest it here. When an
      idea is accepted for implementation, the team will create an issue for tracking the work.
  - name: Suggest a new document or major rewrite of an existing one
    url: https://github.com/microsoft/Documentarian/discussions/new?category=docs-proposals
    about: >-
      If you have an idea for an article or rewrite of existing docs, suggest it here. When an
      idea is accepted for implementation, the team will create an issue for tracking the work.
  - name: Suggest a new blog post or major rewrite of an existing one
    url: https://github.com/microsoft/Documentarian/discussions/new?category=blog-proposals
    about: >-
      If you have an idea for a blog post or rewrite of an existing one, suggest it here. When an
      idea is accepted for implementation, the team will create an issue for tracking the work.
