replacements: >-
  github.com/microsoft/Documentarian/Projects/Hugo/docsy-pwsh -> Hugo/docsy-pwsh,
  github.com/microsoft/Documentarian/Projects/Modules/Documentarian -> Modules/Documentarian,
  github.com/microsoft/Documentarian/Projects/Modules/Documentarian.DevX -> Modules/Documentarian.DevX,
  github.com/microsoft/Documentarian/Projects/Modules/Documentarian.MarkdownBuilder -> Modules/Documentarian.MarkdownBuilder,
  github.com/microsoft/Documentarian/Projects/Modules/Documentarian.MicrosoftDocs -> Modules/Documentarian.MicrosoftDocs,
  github.com/microsoft/Documentarian/Projects/Modules/Documentarian.ModuleAuthor -> Modules/Documentarian.ModuleAuthor,
  github.com/microsoft/Documentarian/Projects/Modules/Documentarian.Vale -> Modules/Documentarian.Vale,
  github.com/microsoft/Documentarian/Projects/Styles/PowerShell-Docs -> Styles/PowerShell-Docs
imports:
  - path: github.com/microsoft/Documentarian/Projects/Modules/Documentarian
    mounts:
      - source: Documentation
        target: content/modules/documentarian
      - source: CHANGELOG.md
        target: content/modules/documentarian/changelog.md
      - source: Source
        target: content/includes/source/documentarian
  - path: github.com/microsoft/Documentarian/Projects/Modules/Documentarian.DevX
    mounts:
      - source: Documentation
        target: content/modules/devx
      - source: CHANGELOG.md
        target: content/modules/devx/changelog.md
      - source: Source
        target: content/includes/source/devx
  - path: github.com/microsoft/Documentarian/Projects/Modules/Documentarian.MarkdownBuilder
    mounts:
      - source: Documentation
        target: content/modules/markdownbuilder
      - source: CHANGELOG.md
        target: content/modules/markdownbuilder/changelog.md
      - source: Source
        target: content/includes/source/markdownbuilder
  - path: github.com/microsoft/Documentarian/Projects/Modules/Documentarian.MicrosoftDocs
    mounts:
      - source: Documentation
        target: content/modules/microsoftdocs
      - source: CHANGELOG.md
        target: content/modules/microsoftdocs/changelog.md
      - source: Source
        target: content/includes/source/microsoftdocs
  - path: github.com/microsoft/Documentarian/Projects/Modules/Documentarian.ModuleAuthor
    mounts:
      - source: Documentation
        target: content/modules/moduleauthor
      - source: CHANGELOG.md
        target: content/modules/moduleauthor/changelog.md
      - source: Source
        target: content/includes/source/moduleauthor
  - path: github.com/microsoft/Documentarian/Projects/Modules/Documentarian.Vale
    mounts:
      - source: Documentation
        target: content/modules/vale
      - source: CHANGELOG.md
        target: content/modules/vale/changelog.md
      - source: Source
        target: content/includes/source/vale
  - path: github.com/microsoft/Documentarian/Projects/Styles/PowerShell-Docs
    mounts:
      - source: Documentation
        target: content/styles/powershell-docs
      - source: Source/.vale.ini
        target: content/includes/source/styles/psdocs/.vale.ini
      - source: CHANGELOG.md
        target: content/styles/powershell-docs/changelog.md
      # Due to a bug in hugo, this currently mounts the rules to the root of the data folder instead
      # of the correct dotpath (in this case 'Rules/Avoid.yml' is mounted to 'site.Data.Avoid'
      # instead of site.Data.styles.psdocs.Avoid').
      - source: Source/Rules
        target: data/styles/psdocs
  - path: github.com/microsoft/Documentarian/Projects/Hugo/docsy-pwsh
  - path: github.com/google/docsy
  - path: github.com/google/docsy/dependencies
