name: Test Modules

on:
  pull_request:
    paths:
      - 'Projects/Modules/*/Source/**'
      - 'Projects/Modules/*/Tests/**'
      - 'Projects/Modules/*/.DevX.jsonc'

defaults:
  run:
    shell: pwsh

jobs:
  test_modules:
    name: PowerShell
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - Documentarian
          - Documentarian.DevX
          - Documentarian.MicrosoftDocs
          - Documentarian.ModuleAuthor
          - Documentarian.Vale
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v3
        with:
          path: '~/.local/share/powershell/Modules'
          key: ${{ runner.os }}-SqlServer-PSScriptAnalyzer
      - name: Install required PowerShell modules
        if: steps.cacher.outputs.cache-hit != 'true'
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild, PlatyPS, PowerShell-Yaml -ErrorAction Stop
      - name: Test ${{ matrix.module }}
        run: |
          $PSVersionTable
          Push-Location ./Projects/Modules
          Invoke-Build
          Push-Location ./${{ matrix.module }}
          Invoke-Build -Task Test
